FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY apelmusic/*.csproj ./apelmusic/

RUN dotnet restore apelmusic/apelmusic.csproj

COPY . .

WORKDIR /src/apelmusic
RUN dotnet build apelmusic.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish apelmusic.csproj -c Release -o /app/publish 

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Expose port
EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "apelmusic.dll"]