FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

#Copy csproj and restore dependencies
COPY ["apelmusic/apelmusic.csproj", "apelmusic/"]
RUN dotnet restore "apelmusic/apelmusic.csproj"

#Copy all files and build
COPY . .
WORKDIR "/src/apelmusic"
RUN dotnet build "apelmusic.csproj" -c Release -o /app/build

# Publish the application
FROM build AS publish
RUN dotnet publish "apelmusic.csproj" -c Release -o /app/publish 

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Create directory for data protection keys
RUN mkdir -p /app/keys
ENV DataProtection__KeyPath=/app/keys

# Expose port
EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "apelmusic.dll"]